name: Azure OIDC Demo

on:
  push:
    branches:
    - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  azure:
    uses: joshjohanning-org/reusable-workflows/.github/workflows/azure-oidc-sample.yml@azure-oidc-claims
    permissions:
      id-token: write # this is needed for oidc
      contents: read # this is needed to clone repo
    with:
      runs-on: ubuntu-latest
    secrets: inherit
